language: python
os:
  - linux
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libbluetooth-dev
  - git submodule update --init
install:
  - python setup.py install
script:
  - python -c "import gattlib"