language: python
os:
  - linux
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libbluetooth-dev libboost-python-dev libboost-thread-dev libglib2.0-dev python-dev build-essential
  - git submodule update --init
install:
  - python setup.py install
script:
  - python -c "import gattlib"